### ISSUE TITLE
python plugins don't work

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/pluma#298]
#### Expected behaviour

Python plugins must work

#### Actual behaviour

Python plugins don't work

#### Steps to reproduce the behaviour

`** (pluma:8812): WARNING **: Could not load Pluma repository: Typelib file for namespace 'Pluma', version '1.0' not found`

_snippets_:

```
(pluma:8812): libpeas-WARNING **: Error importing plugin 'snippets':
Traceback (most recent call last):
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/x86_64-linux-gnu/pluma/plugins/snippets/__init__.py", line 19, in <module>
    from gi.repository import GObject, GLib, Gtk, Peas, Pluma
ImportError: cannot import name Pluma

(pluma:8812): libpeas-WARNING **: Error loading plugin 'snippets'
```

_pythonconsole_:

```
(pluma:8812): libpeas-WARNING **: Error importing plugin 'pythonconsole':
Traceback (most recent call last):
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/x86_64-linux-gnu/pluma/plugins/pythonconsole/__init__.py", line 27, in <module>
    from gi.repository import GObject, Gtk, Peas, Pluma
ImportError: cannot import name Pluma

(pluma:8812): libpeas-WARNING **: Error loading plugin 'pythonconsole'
```

_externaltools_:

```
(pluma:8812): libpeas-WARNING **: Error importing plugin 'externaltools':
Traceback (most recent call last):
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/x86_64-linux-gnu/pluma/plugins/externaltools/__init__.py", line 21, in <module>
    from gi.repository import GObject, Gtk, Peas, Pluma
ImportError: cannot import name Pluma

(pluma:8812): libpeas-WARNING **: Error loading plugin 'externaltools'
```

![pluginsfail](https://user-images.githubusercontent.com/7734191/37208590-297d3588-23a2-11e8-8c5d-5aa0fb607bef.png)

#### MATE general version

1.20

#### Package version

pluma 1.20, and 1.18

#### Linux Distribution

debian testing

**Comment by monsta** [comment]
I have a feeling it's the consequence of [this change](https://anonscm.debian.org/git/pkg-mate/pluma.git/commit/?id=a6de396aecf2446bd59dac7361a9ccee3965143b)...

**Comment by sc0w** [comment]
@monsta no, I reverted it here and the plugins don't work

btw, you can confirm the issue?

**Comment by monsta** [comment]
I can't, but I always build my packages using https://github.com/mate-desktop/debian-packages...

**Comment by sc0w** [comment]
with https://github.com/mate-desktop/debian-packages/tree/master/pluma/debian the same behavior, the python plugins don't work

**Comment by monsta** [comment]
Do you have the GI package installed? `gir1.2-pluma` or `gir1.2-pluma-1.0`

**Comment by sc0w** [comment]
aha, now it works with the package **gir1.2-pluma-1.0**

@monsta thanks a lot
